variable1 = input("First => ")
print(variable1)
variable2 = input("Second => ")
print(variable2)
print("Example variable names")
print("Lower case:",variable1.lower() + "_" + variable2.lower())
print("For constants:",variable1.upper() + "_" + variable2.upper())
print("Camel case:",variable1.capitalize() + "" + variable2.capitalize())
print("System variables:", "_"+variable1.lower() + "_" + variable2.lower())
variable1 = variable1.replace("a","_")
variable1 = variable1.replace("e","_")
variable2 = variable2.replace("a","_")
variable2 = variable2.replace("e","_")
print("Silly variable:", variable1.lower() + "_" + variable2.lower())
